### ISSUE TITLE
error: Precondition check failed

### ISSUE THREAD

**Issue by foolo** [zkemail/registry.prove.email#33]
![photo_2024-02-22_09-05-08](https://github.com/foolo/dkim-lookup/assets/667227/19c6039c-5fdb-492c-bc3c-d82e36e0f9cd)

**Comment by foolo** [comment]
![Screenshot_2024-02-23_09-47-05](https://github.com/foolo/dkim-lookup/assets/667227/e5342df0-d7cb-4612-a7cd-fe7687c8d939)
![Screenshot_2024-02-23_09-49-12](https://github.com/foolo/dkim-lookup/assets/667227/447a35e7-b062-4a12-b63c-8cd23a216bbe)

**Comment by foolo** [comment]
[precond bug logs.txt](https://github.com/foolo/dkim-lookup/files/14395507/precond.bug.logs.txt)

**Comment by foolo** [comment]
@Divide-By-0, has this occurred on other occations than the above?

**Comment by Divide-By-0** [comment]
> @Divide-By-0, has this occurred on other occations than the above? edit: and if yes, has it occured for more than one user?

Haven't seen it elsewhere. We are okay with one domain every now and then failing, ignoring it, then moving on, do we have error handling that does that?

**Comment by foolo** [comment]
> > @Divide-By-0, has this occurred on other occations than the above? edit: and if yes, has it occured for more than one user?
> 
> Haven't seen it elsewhere. We are okay with one domain every now and then failing, ignoring it, then moving on, do we have error handling that does that?

Ok, thanks!
The only two cases where we ignore and move on is when 1. a gmail message is invalid, and 2. when a DNS lookup fails. In other cases, the process is interrupted. It would of course be possible to ignore and move on in more cases, although after consideration in each case, to avoid a situation where we get hundreds of consecutive errors.

Anyway, in this particular issue, ignoring and moving on probably wouldn't have helped, because for some reason the Gmail API stopped accepting requests, and returned "Precondition check failed", but I have not figured out why.

**Comment by foolo** [comment]
Closing for now since there's not much we can do here.
