### ISSUE TITLE
Add signifier in UI to indicate record added from batch job

### ISSUE THREAD

**Issue by foolo** [zkemail/registry.prove.email#73]
Add signifier in UI to indicate that a certain key was added from the batch job from https://github.com/zkemail/registry.prove.email/issues/66

**Comment by foolo** [comment]
Yush G, [2024-04-09 08:23]
Sweet! Let's put them in, and then add some sort of signifier to the UI that indicates whether it's scraped or found from inbox


Yush G, [2024-04-09 08:29]
I think we can effectively assume everything so far has been taken from an inbox

**Comment by Divide-By-0** [comment]
Maybe just put scraped instead of top 1m batch lookup?

**Comment by foolo** [comment]
> I think a line is fine. Maybe just put scraped instead of top 1m batch lookup?

@Divide-By-0 Good suggestion, done!
